### ISSUE TITLE
Execution of multiple commands is hanging

### ISSUE THREAD

**Issue by r4lly** [profesorfalken/jPowerShell#2]
Hi,

since version 1.3.1 the execution of multiple commands per session is hanging. See the following example:

```
    PowerShell ps = PowerShell.openSession();

    for (int i = 0; i < 10; i++) {
        System.out.print("Cycle: " + i);

        String output = ps.executeCommand("date").getCommandOutput().trim();

        System.out.println("\t" + output);
    }
```
    
**Output:**
```
Cycle: 0    Dienstag, 1. März 2016 22:57:23
Cycle: 1    Dienstag, 1. März 2016 22:57:24
Cycle: 2    Dienstag, 1. März 2016 22:57:24
Cycle: 3
```

I haven't debugged it, but think the problem is that the commandProcessor and/or commandProcessorError tasks are still running and locking the threads from the threadpool. Maybe they should be canceled after runnging a command.

In version 1.3.0 the problem was not there, because each execution of a command has created a new threadpool with new threads... That was also not so nice if you are running many commands in a row. ;-)

**Systeminfo:**
```
PS C:\Windows\System32\WindowsPowerShell\v1.0> java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

PS C:\Windows\System32\WindowsPowerShell\v1.0> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

**Comment by profesorfalken** [comment]
Hi r4lly,

In fact, I have never though on use it like that, within a loop. 

Thank you for your super-report. Indeed it seems that the threads are not correctly cancelled so I will try to do it manually after each use.

I will keep you updated.

Thank you!

**Comment by profesorfalken** [comment]
Umm... ok, this is what I get when I execute your example: 

    Cycle: 0	Wed Mar  2 09:00:27 RST 2016
    Cycle: 1	Wed Mar  2 09:00:27 RST 2016
    Cycle: 2	Wed Mar  2 09:00:27 RST 2016
    Cycle: 3

I becomes stuck when processing the cicle 3.

**Comment by profesorfalken** [comment]
I had only 10 minutes to test. I have tried:

-Cancel the results after using them.
-Increase the max threads in the pool to 20
-Insert a thread.sleep of 3 seconds in each loop execution.

In all the causes the result is the same. It hangs in the third cycle.

I will continue to look maybe tonight with a little more of time.

**Comment by profesorfalken** [comment]
Ok, I did not test properly. It works ok when we cancel the results after using them.

I am going to build a version 1.3.2 with this fix.

I will tell you when it is ready in order to confirm the solution.

**Comment by r4lly** [comment]
Thanks for your fast response!

After a short debug-session I've noticed that the resultError task is never ending. For each command execution this task blocks an aditional thread from threadpool if the command on powershell doesn't throw an error.

The commandProcessorError (resultError) task stucks in the startReading()-method forever, because it doesn't check for timeout. If this behavior was intended, the task should be canceled at the end of the executeCommand(String command)-method.

**Comment by profesorfalken** [comment]
> the task should be canceled at the end of the executeCommand(String command)-method.

Yes, as I said in my last post it is exactly that what was wrong. Its fixed and I have add an automatic test to check the 'loop' case.

I have just generated a new version 1.3.2 with the fix. It will take some hours to be available on Maven Central but you can download already here:
https://oss.sonatype.org/content/groups/staging/com/profesorfalken/jPowerShell/1.3.2/jPowerShell-1.3.2.jar

Can you confirm that it works?

Thank you!

**Comment by r4lly** [comment]
Ah, thanks for your work!

Unfortunately, your fix seems not to work all of the time. Sometimes it throws a **java.lang.InterruptedException: sleep interrupted** which is catched by you. So far everything is OK. But when this exception is thrown, the response for the given command is empty. 
It looks like that the response from the current command is added to the response of the next command.

Sadly, the problem is not deterministic. It seems to be a concurrence problem...  Maybe you can reproduce this with the following example:

```
PowerShell powerShell = PowerShell.openSession();
for (int i = 0; i < 100; i++) {
	System.out.print("Cycle: " + i);
	
	Thread.sleep(100);

	PowerShellResponse response = powerShell.executeCommand("date"); // Line 17 (see exception below)

	if (response.isError()) {
		System.out.println("error"); // never called
	}

	String output = "<" + response.getCommandOutput().trim() + ">";

	System.out.println("\t" + output);
}
```
(I used "<" and ">" to show the start and the end of the response)

**Extract of output:**
```
Cycle: 53	<Mittwoch, 2. März 2016 23:37:33>
Cycle: 54	<Mittwoch, 2. März 2016 23:37:33>
Cycle: 55	<>
Cycle: 56Mär 02, 2016 11:37:33 PM com.profesorfalken.jpowershell.PowerShell executeCommand
SCHWERWIEGEND: Unexpected error when processing PowerShell command
java.util.concurrent.ExecutionException: java.lang.InterruptedException: sleep interrupted
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.profesorfalken.jpowershell.PowerShell.executeCommand(PowerShell.java:120)
	at myPowerShellTest.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.profesorfalken.jpowershell.PowerShellCommandProcessor.startReading(PowerShellCommandProcessor.java:87)
	at com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:66)
	at com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	<Mittwoch, 2. März 2016 23:37:33



Mittwoch, 2. März 2016 23:37:34>
Cycle: 57	<Mittwoch, 2. März 2016 23:37:34>
Cycle: 58	<Mittwoch, 2. März 2016 23:37:34>
Cycle: 59	<Mittwoch, 2. März 2016 23:37:34>
```

**Comment by profesorfalken** [comment]
Ok thank you very much for your impressive work finding bugs ;-) 

I think that I have a clue of what it is happening. When I cancel the future task I send a flag to force the interruption. I think that I just have to let the task finish before cancelling.

I will do some tests and I will generate an snapshot version to test the solution.

Thanks a lot!

**Comment by profesorfalken** [comment]
Well, it is not that easy as I though...

I have launched your example a thousand times and it always works OK in my system.

If I try to avoid interrupting when cancel I have the 'hanging' problem in the third cycle.

What I have done is to make an small wait before cancelling in order to make sure that the reading loop is processed. 
Can you check if the problem is now solved for you?

https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.3-SNAPSHOT/jPowerShell-1.3.3-20160303.083919-1.jar

If you confirm it I will generate the 1.3.3 version.

Thanks for your help

**Comment by r4lly** [comment]
Thanks for your fast response and work! 
Maybe you can reproduce the problem by removing the sleep in my main loop.

Your fix prevent the InterruptedException in most cases. Just sometimes the exception is shown in the error log. But the problem with the empty response is still there. Unfortunately, it's difficult to say whether it has now become better with your improvement. I think its a little bit better. 

I have also tested your added sleep with 20ms and 50ms. 50ms seems to work well, but I think this is dependent on the machine and the background workload. Further increasing of the sleep time will also increase the latency of the commands, so I think this is not the best solution.

In some cases the output from main thread looks like this: (Output from Cycle 4 is shifted to Cycle 5, and the output from Cycle 5 is added to Cycle 6)
```
Cycle: 3	<Donnerstag, 3. März 2016 10:02:45>
Cycle: 4	<>
Cycle: 5	<Donnerstag, 3. März 2016 10:02:45>
Cycle: 6	<Donnerstag, 3. März 2016 10:02:46



Donnerstag, 3. März 2016 10:02:46>
Cycle: 7	<Donnerstag, 3. März 2016 10:02:46>
Cycle: 8	<Donnerstag, 3. März 2016 10:02:46>
```
PS: I'm using a system with 2 physical cores, but with HTT (=> 4 logical cores). Maybe your testing system is faster than my system. ;)

**Comment by profesorfalken** [comment]
> PS: I'm using a system with 2 physical cores, but with HTT (=> 4 logical cores). Maybe your testing system is faster than my system. ;)

Well I think that the point is there (n of cores & speed). However, the reason is just the opposite. 
In fact I am a Linux guy and I only use Windows into a Virtual Machine. This virtual machine is configured to only use one core. I think  that this explains why it always works for me.

Apparently the JVM tries to optimize speed and parallelize the loop using several cores. This is what causes the concurrency problem.

I will give more cores to the virtual machine in order to reproduce the problem and will try to control it in the smartest way I can.

I will keep you updated

Thank you very much for your help

**Comment by profesorfalken** [comment]
No luck. Even with two cores I cannot reproduce it. 

My system is slower that your (you have an i3, haven't you) because it is just a Pentium G3258 @ 3.2 with physical two cores and no HTT.

However I have created a new Snapshot which adds some logs to try to understand the problem. 
Could you please test it and tell me if you have logs of type "Cannot cancel result [...]"?

https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.3-SNAPSHOT/jPowerShell-1.3.3-20160303.115506-2.jar

Thank you!

**Comment by r4lly** [comment]
Too bad that you can't reproduce the problem. :(

It's quite possible that the amount of cores has an effect on your code. I'm using an ULV i5 (U4200 @ 1,6 - 2.3GHz) on my Windows machine. In a few days I can also test this code on an another Windows system with an AMD Athlon II X4 631 (4 cores @ 2.6GHz).

I have tested your new snapshot with and without an 100ms sleep in the main loop. Also with the sleep I've got errors (0-2 errors / 100 cycles), but not as much as without sleep (0-4/100).

I've got 2 variants of errors:
```
Cannot cancel result result.isDone(): false resultError.isDone(): true commandOutput.trim():
Cannot cancel result result.isDone(): true resultError.isDone(): false commandOutput.trim():
```
Each time the trimmed commandOutput is empty.

See the attachment for the full output.

[output-1_3_3-SNAPSHOT-2.txt](https://github.com/profesorfalken/jPowerShell/files/157764/output-1_3_3-SNAPSHOT-2.txt)

**Comment by profesorfalken** [comment]
Thank for such a great feedback. In fact, your logs show me that I was mistaken and it was not exactly what I thought.

I will need to bother you even more and ask you a little bit of help.

Could you check this snapshot and tell me if it works?
https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.3-SNAPSHOT/jPowerShell-1.3.3-20160304.161935-3.jar

If not, maybe this works?:
https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.3-SNAPSHOT/jPowerShell-1.3.3-20160304.162218-4.jar

(This last one will take quite long time to execute. It is just a test to understand the cause)

Thank you for your help!

**Comment by r4lly** [comment]
Hi, thanks for your work. I have some good and some bad news for you.

**The bad one:**
Both of your snapshots will produce the known error. The 2 second sleep helps a lot, but sometimes the error is anyway thrown. (3 Fails in over 8000 Cycles):

```
Cycle: 401	<Freitag, 4. M?rz 2016 23:12:28>
Cycle: 402	<Freitag, 4. M?rz 2016 23:12:30>
Cycle: 403M‰r 04, 2016 11:12:34 PM com.profesorfalken.jpowershell.PowerShell executeCommand
SCHWERWIEGEND: Unexpected error when processing PowerShell command
java.util.concurrent.ExecutionException: java.lang.InterruptedException: sleep interrupted
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.profesorfalken.jpowershell.PowerShell.executeCommand(PowerShell.java:122)
	at myPoweShellTest.Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.profesorfalken.jpowershell.PowerShellCommandProcessor.startReading(PowerShellCommandProcessor.java:87)
	at com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:66)
	at com.profesorfalken.jpowershell.PowerShellCommandProcessor.call(PowerShellCommandProcessor.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

M‰r 04, 2016 11:12:34 PM com.profesorfalken.jpowershell.PowerShell executeCommand
SCHWERWIEGEND: Cannot cancel result result.isDone(): true resultError.isDone(): false commandOutput.trim(): 
	<>
Cycle: 404	<Freitag, 4. M?rz 2016 23:12:32



Freitag, 4. M?rz 2016 23:12:34>
Cycle: 405	<Freitag, 4. M?rz 2016 23:12:37>
Cycle: 406	<Freitag, 4. M?rz 2016 23:12:39>
Cycle: 407	<Freitag, 4. M?rz 2016 23:12:41>
```

**Okay, now the good/bad one:**
I have played around with version 1.3.1 of your library (without the cancel calls) and increased the number of threads in the threadpool to 1000. I have run multiple times a 1000 cycles loop without any errors. So it seems that the errors comes from the cancel calls.

**Again a good/bad one:**
I've found a dirty workaround (based on 1.3.1): 
I've integrated a manual cancel flag in your `PowerShellCommandProcessor`:

Line 89:
`if (checkTimeout && timeWaiting > PowerShell.MAX_WAIT) {`
changed to: 
`if ((checkTimeout && timeWaiting > PowerShell.MAX_WAIT) || cancel) {`

I've also added a setter to set the cancel flag, but I'm not sure if the cancel flag has to be volatile.
Before the method `executeCommand(String command)` is ending, i just call the setter method and set the cancel-flag to `true`;

The workaround is working very well for me.

I hope this will help you. Maybe you will find a better solution.

**Comment by profesorfalken** [comment]
Umm have you tested just to declare volatile the variable checkTimeout?

Maybe the variable is stored in CPU cache by the JVM and it is not correctly updated.

**Comment by r4lly** [comment]
I don't touched the variable checkTimeout. The instance variable is also just used by one thread, so i think there is no need for volatile. Furthermore the checkTimeout variable has no impact on the error-task, because you initialize it with false.

I have only added the variable `private volatile boolean cancel = false;` with setter to your CommandProcessor.

**Comment by profesorfalken** [comment]
Yes I have understand your solution.
You are right about the checkTimeout variable since it is an instance variable, but we could say the same for cancel variable dont we?

Nevertheless I have also added in the last snapshot a synchronized block to enclose the reading process. Could you check if it makes any difference?

**Comment by r4lly** [comment]
I'm not sure if we could say the same for the cancel variable because it is accessed by 2 threads. One thread (main) writes and one thread (commandProcesser) reads this value.

In the evening I will check if the syncronized block makes any difference.

**Comment by profesorfalken** [comment]
Well the checkTimeout is similar. It is setted by one thread and accessed by other. The checkTimeout is setted on main using the constructor each time:

    Callable commandProcessor = new PowerShellCommandProcessor("standard", commandWriter, p.getInputStream(), true);
    Callable commandProcessorError = new PowerShellCommandProcessor("error", commandWriter, p.getErrorStream(), false);

**Comment by r4lly** [comment]
Hm, yes. The variable is created by main-thread. But later the commandProcessor is passed to another thread. At this time the variable is never changed by another thread - so no need to synchronize (I'm hope that I'm not wrong). On the other hand the variable is final and can only be set in constructor. Later it cannot be changed.
The cancel variable differs from this, because after changing a volatile variable, the volatile keyword ensures, that all copies of this variables in all threads will be updated.

**Comment by profesorfalken** [comment]
Yes but if it is created in each instance I wouldn't consider it a shared variable... anyway in the worst case it will not do any harm.
I agree also that the synchronized won't change anything since we create a new instance each time so only one thread will access the instance method at a time.

What really worry me is that I do not understand the problem or how your cancel solution can work.

As your logs show, the exception is produced when we perform the result.get and not the result.cancel.

jPowerShell session maintains a poweshell console opened on background and works sending commands and recovering responses. If we perform many command in parallel I can understand that the console can become stuck.

But with the cancel variable, when we set it in that case the startReading() method will return false an thus we are not going to try to read the output in the call() method, so the call will return an empty output. It is not the case?

I do not understand either why increasing the threadpool to 1000 can fix the problem. In each iteration we only need a thread for standard input and another for error input. If it works it means that the real cause is that a thread is hanging even after cancelling. But in this case I do not understand why the 2 seconds sleep has not worked since it should have exit in timeout.

**Comment by profesorfalken** [comment]
Ok finally I have found more than 5 minutes to see it properly and I think I have it.
I have partially reproduce your problem using an static lock on command processor (and I got also the interrupted exception).

Finally I came to a solution very similar to yours and I took the opportunity to remove completely the horrible checkTimeout variable.

Could you take a look please?
https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.3-SNAPSHOT/jPowerShell-1.3.3-20160305.133242-6.jar

Thanks

**Comment by r4lly** [comment]
Hi, you are right. The exception is produced by `result.get()`, but it have to do with `result.cancel(boolean)`. To confirm this, i had increased the threadpool to 1000 (Its not a fix of this problem!). With the threadpool of 1000 and without `result(Error).cancel()` I've got no errors, but the loop always stuck at 1000 cycles, because each cycle needs a new thread. New threads are needed, because the `commandProcessorError` task has no real terminating condition and lives forever. That's why we need to cancel the task with result(Error).cancel(boolean) which interrupts the task.

My workaround does not interrupt the task like the `cancel(boolean)`-method from the `Future`-interface. With the manual cancel flag I let the task terminate "normally". When the task terminates, then will also the thread be released to the threadpool.

Unfortunately, your new SNAPSHOT-6 won't work for me. Sometimes I still get the already known exception. Immediately after you `close()` the `commandProcesser` you try to cancel the result-task, but this is not needed (see explanation above).

But why the exception is still thrown after the close of the `commandProcessor`? Its because you only set the close-flag. At this time the `commandProcessor`-thread is sometimes still in the 10ms sleep. So the task will only terminate, when the thread wake up from the sleep. If the thread is still in sleep and you call the 'cancel()'-method you will get the good old known `InterruptedException`. In this case you don't give the task any chance to terminate, because you just interrupt the task.

I think the problem is solved when you remove the `result(Error).cancel(boolean)`-calls (I still not tested this). I hope I could help you to understand the problem of the last SNAPSHOT.

**Comment by profesorfalken** [comment]
I am lucky of having the help of such a good engineer. Thank you very much for your help.

Yes, after writing the first of my last two posts and when developing the snapshot-6 I understood mostly the problem. However in my artificial tests when setting the close() and even interrupting afterwards, the problem disappeared.

You are completely right. If we perform the close() the cancel/interrupt is not needed anymore since the threads are terminated normally.

Here is the snapshot with the fix: 
https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.3.3-SNAPSHOT/jPowerShell-1.3.3-20160306.111229-7.jar

**Comment by r4lly** [comment]
Wow, now its working as expected!

Thank you very much for this fix and your power of endurance!

PS: I'm not really a good engineer. I'm still a student and have to learn a lot. ;)

**Comment by profesorfalken** [comment]
Cool! I am glad it worked out.

It is amazing to know that your are still an student. Yes, you have a lot to learn (as everybody) but your future is just **brilliant**. Concurrence is not a trivial subject and I can assure you that there are many experienced and well paid engineers that does not even now what does a volatile variable.

Thanks again for your help, I will create & publish the new fixed version right now.
