### ISSUE TITLE
Does not work with PowerShell on linux

### ISSUE THREAD

**Issue by mores** [profesorfalken/jPowerShell#26]
PowerShell is now available on linux: https://github.com/PowerShell/PowerShell

Error logs:
Oct 09, 2017 11:45:26 AM com.profesorfalken.jpowershell.PowerShell executeSingleCommand
SEVERE: PowerShell not available
com.profesorfalken.jpowershell.PowerShellNotAvailableException: Cannot execute PowerShell.exe. Please make sure that it is installed in your system

Powershell is installed on linux:
$ /opt/microsoft/powershell/6.0.0-beta.7/powershell 
PowerShell v6.0.0-beta.7
Copyright (C) Microsoft Corporation. All rights reserved.

PS />

**Comment by profesorfalken** [comment]
Hello @mores, 

I had already commited (not pushed) a version that handled Linux case. 
You can use the 1.9.1 version.

Best regards

**Comment by praveenmathamsetty** [comment]
PWSH
PowerShell v6.0.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /usr/bin> 
-------------------------------------------------------------------
error:
com.profesorfalken.jpowershell.PowerShellNotAvailableException: Cannot execute PowerShell.exe. Please make sure that it is installed in your system
	at com.profesorfalken.jpowershell.PowerShell.initalize(PowerShell.java:112)
	at com.profesorfalken.jpowershell.PowerShell.openSession(PowerShell.java:139)

**Comment by lidenger** [comment]
1 install powershell,detail:https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1
2 this code
`PowerShell powerShell = PowerShell.openSession("pwsh")`

**Comment by mores** [comment]
I can confirm that version 3.1.1 is working on linux.
