### ISSUE TITLE
null file generated

### ISSUE THREAD

**Issue by jflefebvre06** [profesorfalken/jPowerShell#33]
after migration to the last version (1.9.1) when I execute command a file "null" is generated
[null.zip](https://github.com/profesorfalken/jPowerShell/files/1606064/null.zip)

**Comment by profesorfalken** [comment]
Ups! thanks for the warning

I will check it

**Comment by zik43** [comment]
It's really annoying as bug especially when it's a repetitive task because the file grows.

**Comment by profesorfalken** [comment]
That will be fixed in 2.0 version. 
Commit of fix:
https://github.com/profesorfalken/jPowerShell/commit/eeb0f8f4801e4d85f9c556e5c5f9c0fbb1debc26

I will try to release it in next days.

**Comment by profesorfalken** [comment]
Done. It should be fixed in 2.0 version.
