### ISSUE TITLE
Handle PowerShell 6.0 executable which changed to pwsh

### ISSUE THREAD

**Issue by steph-roy** [profesorfalken/jPowerShell#34]
Please provide a configuration option where the linux executable can be forced to 'pwsh' instead of 'powershell' for versions of PowerShell 6.0 and greater.

**Comment by profesorfalken** [comment]
Hello, 

Thanks. I think it will be ok even to make a more generic configuration option (cmdPath) because it can be handy also in windows (for example, if we want to execute an executable different from the default one).
I note it for next version.

Best regards

**Comment by profesorfalken** [comment]
Hello, 
In 2.0 version it is possible to set a different executable. 
Just pass it as an argument of the openSession method.

Best regards
