### ISSUE TITLE
fails on linux (CentOS)

### ISSUE THREAD

**Issue by odedm** [profesorfalken/jPowerShell#37]
powershell is installed as /usr/bin/pwsh

seems that in PowerShell.java it should be :
pb = new ProcessBuilder(powerShellExecutable,"-nologo","-noexit","-Command", "-");
instead of :
pb = new ProcessBuilder(String.format("%s -nologo -noexit -Command -", powerShellExecutable));

**Comment by profesorfalken** [comment]
Thanks for this feedback. I will try to fix it quickly.
