### ISSUE TITLE
executeScript is private 

### ISSUE THREAD

**Issue by hakimMaharmeh** [profesorfalken/jPowerShell#43]
Hi prof,

I need to execute a powershell script with parameters.
But looking at https://github.com/profesorfalken/jPowerShell/blob/master/src/main/java/com/profesorfalken/jpowershell/PowerShell.java
Both functions are private:
private PowerShellResponse executeScript(String scriptPath, String params)

private PowerShellResponse executeScript(BufferedReader srcReader, String params)

So this will never work:
(cf https://github.com/profesorfalken/jPowerShell )
   PowerShell powerShell = PowerShell.openSession();
    String script = "resourcePath/MyScript.ps1"
    String scriptParams = "-Parameter value"

    //Read the resource
    BufferedReader srcReader = new BufferedReader(
                    new InputStreamReader(getClass().getResourceAsStream(script)));

    if (scriptParams != null && !scriptParams.equals("")) {
        response = powerShell.executeScript(srcReader, scriptParams); ///*** ISSUE HERE ****
    } else {
        response =  powerShell.executeScript(srcReader);
    }

Regards

**Comment by rworsnop** [comment]
Was changed in 6ffb489704556b2f0d8cb60b9b60bd283e321125. No idea why.

**Comment by profesorfalken** [comment]
Hi, 

It is strange. I guessI had passed an static code analyser that suggested changing the visibility of the method.

I will revert this. Thanks for reporting it

Best regards.

**Comment by profesorfalken** [comment]
Fixed in 2.1.1
