### ISSUE TITLE
What is the best way to pass arguments to PS1 script using jpowershell?

### ISSUE THREAD

**Issue by violant** [profesorfalken/jPowerShell#47]
1. I need to pass several arguments to my PS1 script and thess arguments are variables, so I can't hardcode them to PS1. 
What is the best way to do it?

2. How to add Environment variables to script execution in format ENV1='test1'?

**Comment by profesorfalken** [comment]
Hello, 

Can you provide an example of each case in Powershell systax? How will you write it in PowerShell console?

In order to set Environment variables you cannot simply call SetEnvironmentVariable using executeCommand?

Best regards

**Comment by violant** [comment]
Here is simple example of using parameters with powershell script:

.\test.ps1 -Bogus FooBar -FileName "c:\windows\notepad.exe"


```
# Show how to handle command line parameters in Windows PowerShell
param(
  [string]$FileName,
  [string]$Bogus
)
write-output 'This is param FileName:'+$FileName
write-output 'This is param Bogus:'+$Bogus
```

**Comment by violant** [comment]
I mean[ProcessBuilder]( https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#environment() ) for child process envs .
For example if I have script that read envs, so I can add this envs to powershell session.
It is rare case

**Comment by profesorfalken** [comment]
I do not undestand. Since 2.1.1 version, the executeScript methods with parameters is public.
https://github.com/profesorfalken/jPowerShell/releases

What version of jPowerShell are you using?


We can discuss about envs parameter in another separated issue maybe?

**Comment by violant** [comment]
You are right. I used old version. I close this issue
