### ISSUE TITLE
If powershell command execute less then maxWait time then why it will wait for maxWait time

### ISSUE THREAD

**Issue by amit210001** [profesorfalken/jPowerShell#49]
In my case , i have command which took around 1hr 30 minutes and i am using the same method to execute the other command as well which take more then 2 hr to 30 min and if i assign maxWait =3h then it will wait for maximum 3 hrs but command already executed in 1hr .

Is there any way to stop waiting for remaining hrs once the command executed successfully ?

**Comment by profesorfalken** [comment]
Hello, 

Umm, maybe jPowershell cannot detect the end of your script properly. Does your script gives any output? Is it a remote call?

Best regards

**Comment by amit210001** [comment]
I had executed powershell command instead of powershell script and in response.getCommandOutput() it will show the path with the file name which have downloaded from azure . Not its not a remote call.

**Comment by profesorfalken** [comment]
Hello, 

Are you performaing a _System.Net.WebClient).DownloadFile_ then?
Ideally, I would need the exact command so I can reproduce it.

Normally, jPowershell shoul stop once the command stops and not wait until a timeout occurs.

Best regards

**Comment by amit210001** [comment]
just try this command "Get-Content filename -TotalCount 1000001 | Set-Content filename"  and config.put("maxWait", "500000") and it will wait till 500000s but same command executed in 2 minute

**Comment by profesorfalken** [comment]
Ok I will check that

**Comment by amit210001** [comment]
yupe , it didn't return any output , as i mentioned in my previous thread , i am using below command to download the file from azure data lake 

Export-AzureRmDataLakeStoreItem -AccountName accountName -Path pathofthefile -Destination locationofthefilewhichexported which return the output as file name which i have downloaded from azure data lake

Would you please this.

**Comment by amit210001** [comment]
Please close this i have figure out the issue as i am running the AZURE ADF from powershell and it will return some code so my command didn't wait for maxWait time.
