### ISSUE TITLE
Internal mode set by executeScript / closing ressources by executeScript

### ISSUE THREAD

**Issue by JUGI4U** [profesorfalken/jPowerShell#61]
Hi,

first of all, thanks for this library! 
It greatly facilitates access to PowerShell.

There seems to be an issue when executeCommand is called after executeScript during the same session.
In executeScript an internal flag 'scriptMode' is set to true but never reset to false on method exit.
So following plain calls to executeCommand use PowerShellCommandProcessor as if it runs in scriptMode.
These calls usually fail.

Another point is, that in executeScript(String scriptPath, String params), a BufferedReader is opened but seems to be never closed.

Could you please check both issues.
Thanks

Juergen

**Comment by profesorfalken** [comment]
Hello Juergen, 

Thanks for reporting it. I will check & fix it when possible.

Best regards

**Comment by profesorfalken** [comment]
Both bugs are fixed in the new version: https://github.com/profesorfalken/jPowerShell/releases/tag/v3.1.1

So I close this issue.

Thank you!
