### ISSUE TITLE
Executing command timeout

### ISSUE THREAD

**Issue by leiffriis** [profesorfalken/jPowerShell#7]
Hi 

We are using jPowerShell to stop windows service, and waiting for the status to switch with following command (“foreach($service in (Get-Service -Computer ipAdress -Name serviceName)) {$service.stop(); $service.WaitForStatus("Stopped",'00:00:30')}”) 
Sometimes it takes longer than 10 seconds for the service to stop and then we get and timeout in jPowerShell before the command returns.
Is it possible to get a change where we can set the MAX_WAIT? Maybe as a parameter to openSession?

Thanks

**Comment by profesorfalken** [comment]
Hello, 

Yes, I have to take a look to see how to override the MAX_WAIT... I will keep you updated. 

Thanks

**Comment by profesorfalken** [comment]
Hi again, 

Could you test this?
https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.5-SNAPSHOT/jPowerShell-1.5-20160531.184520-1.jar

I have added a mechanism to configure jPowershell. 

- You can configure it **by project** creating a jpowershell.properties file in the classpath of your project and settings the variables you want to override.

- Or you can configure it **by call** using a map that can be chained to powershell call.

For example, in your case:

    Map<String, String> myConfig = new HashMap<>();
    myConfig.put("maxWait", "30000");
    PowerShell powerShell = PowerShell.openSession();
    
    PowerShellResponse response = powerShell.configure(myConfig).executeCommand("Get-Process");

Or directly: 
    PowerShellResponse response = PowerShell.openSession().configure(myConfig).executeCommand("Get-Process");


The three variables that can be configured are: 
_maxThreads_: the maximum number of thread to use in pool. 3 is an optimal and default value
_waitPause_: the pause in ms between each loop pooling for a response. Default value is 10
_maxWait_: the maximum wait in ms for the command to execute. Default value is 10000


Tell me if it works

**Comment by leiffriis** [comment]
Hi

Thanks for your fast response.

I have tried the solution with the property file but did not succeed, I can’t find any references to the PowerShellConfig class.

The configure method on PowerShell works but there is a bug in the PowerShellCommandProcessor.startReading where Thread.sleep are using maxWait instead of waitPause and this make it very difficult to test.

Thanks

**Comment by profesorfalken** [comment]
Ups! I had to generate the jar quickly and I had no time to write tests (and, moreover, I did not have access to a Windows machine). 
I will generate today a new version correctly tested.

**Comment by profesorfalken** [comment]
Hello again, 

It should be all right now for both the config file and the bug in the variable maxWait

https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.5-SNAPSHOT/jPowerShell-1.5-20160601.204944-2.jar

**Comment by leiffriis** [comment]
Hi again

Now it’s working as expected!

Thank you very much for your work

**Comment by profesorfalken** [comment]
Great! 

I have created a 1.5 version that includes this feature. It is already published in Maven Central.

I close this issue.

Thank you
