### ISSUE TITLE
Premature script termination.

### ISSUE THREAD

**Issue by suhail-sullad** [profesorfalken/jPowerShell#9]
I have a ps1 script that downloads file from external website.

following is command
(New-Object System.Net.WebClient).DownloadFile($downloadURL,$savePath)

As the above command blocks the current thread and jpowershell polls for command output every 10ms 
.jpowershell session is terminated immediately after the downloadfile command is invoked. Shouldn't it wait for the DownloadFile command to complete the execution?

**Comment by profesorfalken** [comment]
Hello, 

You can configure the timeout as explained in PowerShell page (_Configure jPowerShell Session_): https://github.com/profesorfalken/jPowerShell

In your case you can just set a very long timeout value in order to let your script finish. 

Regards

**Comment by suhail-sullad** [comment]
I have already configured timeout to 5minutes. However  the function continueRead returns false.   And jpowershell exits.

**Comment by profesorfalken** [comment]
Hello, 
Could you show the code you use to increase the timeout?

Thank you

**Comment by suhail-sullad** [comment]
This is code to execute powershell command
`Map<String, String> myConfig = new HashMap<>();`
`myConfig.put("maxWait", "300000");
 myConfig.put("waitPause", "1000"); `

`PowerShell psSession = PowerShell.openSession();`
`String output = psSession.configuration(myConfig).executeCommand("./myscript.ps1").getCommandOutput()`


This is my ps1 script

`$existingInstallation=Get-WmiObject -Class Win32_Product -Filter "Name = 'opera'"`
`if( -Not ([string]::IsNullOrEmpty($existingInstallation)) )`
`{ Write-Host "Uninstalling existing opera at:"($existingInstallation.InstallLocation);`
`	$existingInstallation.Uninstall();}`
`$downloadURL=$args[0];`
`if( -Not ([string]::IsNullOrEmpty($downloadURL)) )`
`{$opera=$downloadURL.substring($downloadURL.LastIndexOf('/')+1);`
`$operaexe="$env:temp\$opera"`
`Write-Host "downloading : $opera"`
`(New-Object System.Net.WebClient).DownloadFile($downloadURL,$operaexe);`
`Write-Host "download complete!"`

The jpowershell test works when i run following command.
`(New-Object System.Net.WebClient).DownloadFile($downloadURL,$operaexe);`

However in script it fails to execute and terminates prematurely after
`Write-Host "downloading : $opera"`

**Comment by profesorfalken** [comment]
Ok seems that when jPowershell detects that the script returns anything it stops processing.
I will take a look in the next days in order to handle this case. 

As a workaround you can simply comment/remove the _Write-Host "downloading : $opera"_ line from your script and it should work.

**Comment by profesorfalken** [comment]
Hi, 

I have tested a script with this code: 

    Write-Host "First message"
    $output = "c:\10meg.test"
    (New-Object System.Net.WebClient).DownloadFile("http://ipv4.download.thinkbroadband.com/10MB.zip",$output)
    Write-Host "Finish!"

Without issues. jPowershell closes normally and the file is downloaded. 
In my case it takes 15 seconds to download so I set the config of maxWait to 30000.

However it is true that I see something extrange in the behaviour of readData. I will keep you updated if I find something....

**Comment by suhail-sullad** [comment]
For smaller sized files. It is nearly unnoticed. But fails for large file downloads and lose control over the script execution.

**Comment by profesorfalken** [comment]
Does it work if you delete/comment the line Write-Host "downloading : $opera"  in your script?

**Comment by suhail-sullad** [comment]
Yes. It does work

**Comment by profesorfalken** [comment]
Ok, I know what happens but it is not easy to fix and it will take a little bit of time.
I will keep you updated.

**Comment by profesorfalken** [comment]
Hello again, 

Your script should work OK in JPowerShell v1.6 with the new method _executeScript()_.

Could you test it and tell me if it works OK?

Thanks

**Comment by suhail-sullad** [comment]
Hello,
script based execution is working for non parameterized scripts.
 i tested one scenario where script takes parameters

ex: ./downloadfile.ps1 <download_url>

this still falls back to executeCommand() function instead of executeScript()

**Comment by profesorfalken** [comment]
Ok you are right. I forgot to handle the case with parameters. 
I will fix it soon.

Thanks

**Comment by profesorfalken** [comment]
Normally it should be ok with the version 1.6.1. It has a overloaded method _executeCommand_ that allows to have parameters.

Please, tell me if it finally works.

Thanks

**Comment by suhail-sullad** [comment]
Yes both functions are working as expected. On a side note we might need to add a check if there is a provision to execute script s from power shell console. 
I tested on another system 
Where set-executionpolicy variable was not set.
This caused script to fail.

**Comment by profesorfalken** [comment]
Hello, 

I do not think that it is up to jPowerShell the task of arbitrarily modify/escalate the rights or the policies. 

If you want to modify the execution policy or the rights of the user, you could perfectly do it in the same jPowerShell session using the executeCommand() before calling the script, for example.

Regards

**Comment by suhail-sullad** [comment]
the idea was to execute get-executionpolicy and if it matches some predefined policy then go ahead and execute script. However i think the powershell process itself will output the error via STDERR

**Comment by profesorfalken** [comment]
Hello, 

It should be fixed in the 1.6.2 version. Could you check it, please?

Thanks

**Comment by profesorfalken** [comment]
Closed by expiration
